### ISSUE TITLE
Do you still support and update this repository?

### ISSUE THREAD

**Issue by alisalehi1380** [gisooNasr/laravel-design-patterns#3]
Ms.gisuNasr Hello and happy new year. 🎉

Do you still support and update this repository? 🤔
I would like to make some changes and submit a "PR".
@gisuNasr

**Comment by gisuNasr** [comment]
> Ms.gisuNasr Hello and happy new year. 🎉
> 
> Do you still support and update this repository? 🤔 I would like to make some changes and submit a "PR". @gisuNasr

Thank you for reaching out!you're welcome to fork the repository, make your desired changes, and submit a pull request. I'll do my best to review and merge it as soon as possible. Let me know if you have any questions or need assistance with the process

**Comment by alisalehi1380** [comment]
@gisuNasr 
good morning Ms.gisuNasr and tnks for replying 😅
ok, good ✌️
